// Database migration runner for the packaged desktop app.
//
// The installer ships every Prisma migration in resources/db/migrations.json
// ([{ name, sql, checksum }], generated by scripts/electron-build.js step 5).
// On every launch against our own bundled database, electron/postgres.js calls
// runMigrations() so an in-place upgrade picks up migrations added since the
// customer first installed. Before this existed, the schema was applied only
// on first run, so an upgraded install 500'd on the first query touching a new
// column.
//
// Tracking uses Prisma's own "_prisma_migrations" table, written in Prisma's
// row format, so `npx prisma migrate status` / `deploy` agree with this runner
// (office PM2 / external databases, hardware transfers, diagnosis).
//
// Three database states:
//   empty   — no "User" table and no tracking table: first run, apply everything.
//   tracked — tracking table exists: apply bundle migrations it doesn't list.
//   legacy  — "User" exists but no tracking table: an install created from the
//             old concatenated schema.sql. The baseline is the longest prefix of
//             LEGACY_PROBES whose probes all pass; those are recorded without
//             running, the rest run.
//
// Never edit a migration that has shipped: its checksum is recorded here and
// by Prisma, and the SQL has already run on customer databases.

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

// Frozen. One probe per migration that existed before tracking was added —
// each returns a single boolean column `ok`. Migrations added from now on need
// no probe: any database old enough to lack them was already given the
// tracking table by this runner. Longest *prefix* (not newest passing probe)
// matters: the two removal probes also pass on a database so old it never had
// the column in the first place.
const colExpr = (table, column) =>
  `EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() ` +
  `AND table_name = '${table}' AND column_name = '${column}')`;
const colExists = (table, column) => `SELECT ${colExpr(table, column)} AS ok`;
const colAbsent = (table, column) => `SELECT NOT ${colExpr(table, column)} AS ok`;
const relExists = (name) => `SELECT to_regclass('"${name}"') IS NOT NULL AS ok`;

const LEGACY_PROBES = [
  { name: '20260629023937_add_must_change_password', sql: colExists('User', 'mustChangePassword') },
  { name: '20260702010729_add_recurring_jobs', sql: relExists('RecurringJobTemplate') },
  { name: '20260705014326_add_login_lockout', sql: colExists('User', 'failedLoginAttempts') },
  { name: '20260709182935_add_plus_tier_license_crm_invoicing', sql: relExists('Invoice') },
  { name: '20260715192857_add_sync_review_item', sql: relExists('SyncReviewItem') },
  { name: '20260907204516_add_quoting', sql: relExists('Quote') },
  { name: '20260909160000_report_builder', sql: relExists('SavedReport') },
  { name: '20260909170000_report_builder_job_index', sql: relExists('Job_status_scheduledDate_idx') },
  { name: '20260911120000_remove_license_tier', sql: colAbsent('License', 'tier') },
  { name: '20260911130000_add_applied_op', sql: relExists('AppliedOp') },
  { name: '20260911140000_remove_quote_public_token', sql: colAbsent('Quote', 'publicToken') },
  { name: '20260913094753_add_is_service_to_inventory_item', sql: colExists('InventoryItem', 'isService') },
  { name: '20260923120000_dispatch_arrival_time_contact_phone', sql: colExists('Job', 'arrivalTime') },
];

// Byte-for-byte Prisma's own DDL for its tracking table.
const TRACKING_TABLE_DDL = `CREATE TABLE IF NOT EXISTS "_prisma_migrations" (
    "id"                    VARCHAR(36) PRIMARY KEY NOT NULL,
    "checksum"              VARCHAR(64) NOT NULL,
    "finished_at"           TIMESTAMPTZ,
    "migration_name"        VARCHAR(255) NOT NULL,
    "logs"                  TEXT,
    "rolled_back_at"        TIMESTAMPTZ,
    "started_at"            TIMESTAMPTZ NOT NULL DEFAULT now(),
    "applied_steps_count"   INTEGER NOT NULL DEFAULT 0
)`;

// Build time (scripts/electron-build.js step 5): every prisma/migrations/<name>/migration.sql,
// sorted, with Prisma's checksum (sha256 hex of the file bytes).
function buildBundle(migrationsDir) {
  return fs
    .readdirSync(migrationsDir)
    .filter((d) => fs.existsSync(path.join(migrationsDir, d, 'migration.sql')))
    .sort()
    .map((name) => {
      const bytes = fs.readFileSync(path.join(migrationsDir, name, 'migration.sql'));
      return { name, sql: bytes.toString('utf8'), checksum: crypto.createHash('sha256').update(bytes).digest('hex') };
    });
}

function loadBundle(file) {
  const bundle = JSON.parse(fs.readFileSync(file, 'utf8'));
  if (!Array.isArray(bundle) || bundle.some((m) => !m.name || typeof m.sql !== 'string' || !m.checksum)) {
    throw new Error(`Migration bundle ${file} is malformed — reinstall WhiteVanOps.`);
  }
  return [...bundle].sort((a, b) => a.name.localeCompare(b.name));
}

/**
 * Pure: decides what to record and what to run.
 * - appliedNames: Set of names already tracked (tracked state), else null.
 * - legacyPrefixLength: number of LEGACY_PROBES that passed in order (legacy
 *   state), else null. Both null = empty database.
 */
function planMigrations({ bundle, appliedNames, legacyPrefixLength }) {
  const bundleNames = bundle.map((m) => m.name);
  let baseline = [];
  let done = new Set();
  if (appliedNames) {
    done = appliedNames;
  } else if (legacyPrefixLength !== null && legacyPrefixLength !== undefined) {
    baseline = LEGACY_PROBES.slice(0, legacyPrefixLength)
      .map((p) => p.name)
      .filter((n) => bundleNames.includes(n));
    done = new Set(baseline);
  }
  const pending = bundleNames.filter((n) => !done.has(n));
  const unknown = appliedNames ? [...appliedNames].filter((n) => !bundleNames.includes(n)).sort() : [];
  return { baseline, pending, unknown };
}

async function queryBool(client, sql) {
  const { rows } = await client.query(sql);
  return rows[0] && rows[0].ok === true;
}

async function legacyPrefixLength(client) {
  let n = 0;
  for (const probe of LEGACY_PROBES) {
    if (!(await queryBool(client, probe.sql))) break;
    n++;
  }
  return n;
}

function trackingRow(m, stepsCount) {
  return {
    text:
      'INSERT INTO "_prisma_migrations" ("id","checksum","finished_at","migration_name","started_at","applied_steps_count") ' +
      'VALUES ($1,$2,now(),$3,now(),$4)',
    values: [crypto.randomUUID(), m.checksum, m.name, stepsCount],
  };
}

/**
 * Brings the connected database up to the bundle. `beforeApply(pendingNames)`
 * runs (and may throw to abort) before the first schema change on a
 * non-empty database — postgres.js uses it for the pre-upgrade dump.
 * Returns { state, baseline, applied, unknown }.
 */
async function runMigrations({ client, bundle, beforeApply = async () => {}, log = () => {} }) {
  const tracked = await queryBool(client, relExists('_prisma_migrations'));
  const hasUsers = await queryBool(client, relExists('User'));
  const state = tracked ? 'tracked' : hasUsers ? 'legacy' : 'empty';

  let appliedNames = null;
  let prefix = null;
  if (state === 'tracked') {
    const { rows } = await client.query(
      'SELECT migration_name, finished_at, rolled_back_at FROM "_prisma_migrations"'
    );
    const failed = rows.filter((r) => !r.finished_at && !r.rolled_back_at);
    if (failed.length > 0) {
      throw new Error(
        `Database upgrade blocked: migration ${failed[0].migration_name} is recorded as failed from an earlier attempt. ` +
        'See MANUAL_Troubleshooting.md ("Database upgrade failed").'
      );
    }
    appliedNames = new Set(rows.filter((r) => r.finished_at && !r.rolled_back_at).map((r) => r.migration_name));
  } else if (state === 'legacy') {
    prefix = await legacyPrefixLength(client);
    if (prefix === 0) {
      throw new Error(
        'Database upgrade blocked: the existing database schema is not one WhiteVanOps recognises, so it was left untouched. ' +
        'See MANUAL_Troubleshooting.md ("Database upgrade failed").'
      );
    }
  }

  const { baseline, pending, unknown } = planMigrations({ bundle, appliedNames, legacyPrefixLength: prefix });
  if (unknown.length > 0) {
    log(`Database has migrations this build does not know (newer build installed before?): ${unknown.join(', ')} — leaving them alone.`);
  }
  if (baseline.length === 0 && pending.length === 0) {
    return { state, baseline, applied: [], unknown };
  }

  if (pending.length > 0 && state !== 'empty') {
    await beforeApply(pending);
  }

  const byName = new Map(bundle.map((m) => [m.name, m]));

  await client.query('BEGIN');
  try {
    await client.query(TRACKING_TABLE_DDL);
    for (const name of baseline) {
      await client.query(trackingRow(byName.get(name), 0));
    }
    await client.query('COMMIT');
  } catch (err) {
    await client.query('ROLLBACK').catch(() => {});
    throw new Error(`Database upgrade failed while recording existing schema: ${err.message}`);
  }
  if (baseline.length > 0) log(`Recorded ${baseline.length} migration(s) already present in this database.`);

  const applied = [];
  for (const name of pending) {
    const m = byName.get(name);
    await client.query('BEGIN');
    try {
      await client.query(m.sql);
      await client.query(trackingRow(m, 1));
      await client.query('COMMIT');
    } catch (err) {
      await client.query('ROLLBACK').catch(() => {});
      const done = applied.length ? ` Migrations applied before it: ${applied.join(', ')}.` : '';
      throw new Error(`Database upgrade failed at migration ${name}: ${err.message}. That migration was rolled back.${done}`);
    }
    applied.push(name);
    log(`Applied migration ${name}`);
  }
  return { state, baseline, applied, unknown };
}

/**
 * pg_dump (custom format) into `dir`, keeping the newest `keep` dumps.
 * Throws if the dump fails — the caller must not migrate without it.
 */
function dumpBeforeUpgrade({ pgDumpExe, port, user, password, dbName, dir, label, keep = 3 }) {
  if (!fs.existsSync(pgDumpExe)) {
    throw new Error(`Database upgrade aborted: cannot take a pre-upgrade backup (pg_dump not found at ${pgDumpExe}). Nothing was changed.`);
  }
  fs.mkdirSync(dir, { recursive: true });
  const stamp = new Date().toISOString().replace(/[:.]/g, '-');
  const file = path.join(dir, `${stamp}-before-${label}.dump`);
  try {
    execFileSync(pgDumpExe, ['-h', '127.0.0.1', '-p', String(port), '-U', user, '-d', dbName, '--format=c', '--file', file], {
      env: { ...process.env, PGPASSWORD: password },
      stdio: ['ignore', 'ignore', 'pipe'],
      windowsHide: true,
    });
  } catch (err) {
    try { fs.rmSync(file, { force: true }); } catch { /* nothing written */ }
    const detail = err.stderr ? String(err.stderr).trim() : err.message;
    throw new Error(`Database upgrade aborted: the pre-upgrade backup failed (${detail}). Nothing was changed.`);
  }
  const dumps = fs.readdirSync(dir).filter((f) => f.endsWith('.dump')).sort();
  for (const old of dumps.slice(0, Math.max(0, dumps.length - keep))) {
    try { fs.rmSync(path.join(dir, old), { force: true }); } catch { /* best effort */ }
  }
  return file;
}

module.exports = { LEGACY_PROBES, TRACKING_TABLE_DDL, buildBundle, loadBundle, planMigrations, runMigrations, dumpBeforeUpgrade };
